# /Users/morifen/github/dotfiles-latest/brew/00-base/Brewfile
# https://github.com/marcbernardoni/dotfiles-latest/blob/main/brew/00-base/Brewfile

# Adding taps (repo) on top as I was getting errors
# tap "FelixKratz/formulae"
#tap "nikitabobko/tap"

cask "logi-options+"			# Logitech Options+ Software for Logitech devices
cask "dockfix"				    # DockFix Dock replacement

# Fonts
cask "font-meslo-lg-nerd-font"
cask "sf-symbols"
cask "font-jetbrains-mono-nerd-font"

# Editors and IDEs
cask "neovide-app"			    # No Nonsense Neovim
cask "visual-studio-code"		# Microsoft Visual Studio Code, VS Code Open-source code editor

# Browsers
cask "google-chrome"			# Google Chrome web browser
cask "firefox"				    # Mozilla Firefox web browser
cask "brave-browser"		    # Brave web browser
cask "opera"				    # Opera web browser
cask "vivaldi"			        # Vivaldi web browser

# Terminals
cask "ghostty"                   # Terminal emulator that uses platform-native UI and GPU acceleration     


# brew "wget"			        # Internet file retriever
# brew "fzf"			        # Command-line fuzzy finder written in Go
brew "git"			            # Distributed revision control system
# brew "node"			        # Also known as: node.js, node@24, nodejs, npm
# brew "starship"			    # Cross-shell prompt for astronauts
# brew "tmux"			        # Terminal multiplexer
# brew "tree"			        # Display directories as trees (with optional color/HTML output)
# brew "watch"			    # Executes a program periodically, showing output fullscreen
# brew "yarn"			        # JavaScript package manager
# brew "zoxide"			    # Shell extension to navigate your filesystem faster
# brew "bat"			        # Clone of cat(1) with syntax highlighting and Git integration
# brew "eza"			        # Modern, maintained replacement for ls
# brew "zsh-autosuggestions"	# Fish-like fast/unobtrusive autosuggestions for zsh
# brew "zsh-vi-mode"		    # Better and friendly vi(vim) mode plugin for ZSH
# brew "wordnet"			    # Lexical database for the English language

# cask "kitty"			    # GPU-based terminal emulator
# cask "wezterm"			    # GPU-accelerated cross-platform terminal emulator and multiplexer
# cask "ghostty"			    # Terminal emulator that uses platform-native UI and GPU acceleration
# cask "coconutbattery"		# Tool to show live information about the batteries in various devices
# cask "aerospace"            # AeroSpace is an i3-like tiling window manager for macOS

# brew "jq"			        # Lightweight and flexible command-line JSON processor
# brew "sketchybar"		    # Highly flexible, customizable, fast and powerful status bar
